services:
  reverse-proxy:
    container_name: tremolo-reverse-proxy
    image: traefik:v3.1
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080" # Traefik dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  web:
    container_name: tremolo-web
    build:
      context: .
      dockerfile: ./.docker/web/Dockerfile
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`tremolo.localhost`)"
      - "traefik.http.services.frontend.loadbalancer.server.port=80"
    volumes:
      - .:/var/www/html
  
  app:
    container_name: tremolo-app
    build:
      context: .
      dockerfile: ./.docker/app/Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - node_modules:/var/www/html/node_modules
      - .:/var/www/html
  
  db:
    container_name: tremolo-db
    build:
      context: .
      dockerfile: ./.docker/db/Dockerfile
    environment:
      - MYSQL_ROOT_PASSWORD=db
      - MYSQL_DATABASE=db
      - MYSQL_USER=db
      - MYSQL_PASSWORD=db
    volumes:
      - db_data:/var/lib/mysql

volumes:
  node_modules:
  db_data:
